// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApiTest.Models;

namespace WebApiTest.Data2
{
    public partial class PowerAppContext : DbContext
    {
        public PowerAppContext()
        {
        }

        public PowerAppContext(DbContextOptions<PowerAppContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MsReclamationweb> MsReclamationweb { get; set; }
        public virtual DbSet<Ms_Contactsite> Ms_Contactsite { get; set; }
		protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MsReclamationweb>(entity =>
            {
                entity.ToTable("MS_RECLAMATIONWEB");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Client)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("client");

                entity.Property(e => e.Collaborateur)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Date)
                    .HasColumnType("date")
                    .HasColumnName("date");

                entity.Property(e => e.Daterep)
                    .HasColumnType("date")
                    .HasColumnName("daterep");

                entity.Property(e => e.Description)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Flag1)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("FLAG1");

                entity.Property(e => e.Flag2)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("FLAG2");

                entity.Property(e => e.Image)
                    .HasColumnType("image")
                    .HasColumnName("image");

                entity.Property(e => e.Rep)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Type)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("TYPE");
            });
		
			OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}