// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApiTest.Models;

namespace WebApiTest.Data
{
    public partial class NOVOPHARMAContext : DbContext
    {
        public NOVOPHARMAContext()
        {
        }

        public NOVOPHARMAContext(DbContextOptions<NOVOPHARMAContext> options)
            : base(options)
        {
        }
        public virtual DbSet<F_Article> F_Article { get; set; }
        public virtual DbSet<F_Famille> F_Famille { get; set; }
        public virtual DbSet<MbArticle> MbArticle { get; set; }
        public virtual DbSet<MbDocligne> MbDocligne { get; set; }
        public virtual DbSet<MbMouv> MbMouv { get; set; }
        public virtual DbSet<MsAArticle> MsAArticle { get; set; }
        public virtual DbSet<MBAArticle> MBAArticle { get; set; }
        public virtual DbSet<ComFact> ComFacts { get; set; }

        public virtual DbSet<MsAArticleCommercial> MsAArticleCommercial { get; set; }
        public virtual DbSet<MsAArticles> MsAArticles { get; set; }
        public virtual DbSet<MsAClients> MsAClients { get; set; }
        public virtual DbSet<MsAEntt> MsAEntt { get; set; }
        public virtual DbSet<MsALigne> MsALigne { get; set; }
        public virtual DbSet<MsAMarques> MsAMarques { get; set; }
        public virtual DbSet<MsAPiece> MsAPiece { get; set; }
        public virtual DbSet<MsAPointage> MsAPointage { get; set; }
        public virtual DbSet<MsATiers> MsATiers { get; set; }
        public virtual DbSet<MsArticlesFinal> MsArticlesFinal { get; set; }
        public virtual DbSet<MsTiers> MsTiers { get; set; }
        public virtual DbSet<View1> View1 { get; set; }
        public virtual DbSet<LoginRequest> Authentication { get; set; }
        public virtual DbSet<DetailArticle> DetailArticle { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
        public virtual DbSet<MB_ART> MB_ARTS { get; set; }
        public virtual DbSet<F_Lotserie> F_Lotserie { get; set; }
        public virtual DbSet<F_Docligne> F_Docligne { get; set; }
        public virtual DbSet<GiftAssignment> GiftAssignments { get; set; }
        public DbSet<GiftOrder> GiftOrders { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {


            modelBuilder.Entity<GiftAssignment>()
                .ToTable("GiftAssignment"); // Nom de la table en base de données
            modelBuilder.Entity<MBAArticle>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MB_A_ARTICLE");

                entity.Property(e => e.ArDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("AR_Design");

                entity.Property(e => e.ArPrixAch)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PrixAch");


                entity.Property(e => e.ArPrixVen)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PrixVen");

                entity.Property(e => e.Nouveaute)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("Nouveauté");
             
                entity.Property(e => e.Recommande)
                .HasColumnName("Recommandé");

                entity.Property(e => e.ArPunet)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PUNet");

                entity.Property(e => e.ArRef)
                    .IsRequired()
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.AR_CodeBarre)
                 .HasMaxLength(19)
                 .IsUnicode(false)
                 .HasColumnName("AR_CodeBarre");

                entity.Property(e => e.FaCodeFamille)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("FA_CodeFamille");

                entity.Property(e => e.Marque)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ComFact>(entity =>
            {
                entity.HasNoKey();
                entity.ToView("COM_FACT");
            });


            modelBuilder.Entity<Facture>(entity =>
            {
                entity.ToTable("Facture"); // Nom de la table

                entity.HasKey(f => f.Id); // Définir la clé primaire
                                          // Configuration des colonnes
                entity.Property(e => e.Id).HasColumnName("id");
                entity.Property(e => e.Nom).HasColumnName("nom").HasMaxLength(255);
                entity.Property(e => e.Path).HasColumnName("path").HasMaxLength(500);
                entity.Property(e => e.CodePharmacie).HasColumnName("code_pharmacie").HasMaxLength(50);
                entity.Property(e => e.NomPharmacie).HasColumnName("nom_pharmacie").HasMaxLength(255);
                entity.Property(e => e.NomDermo).HasColumnName("nom_dermo").HasMaxLength(255);
                entity.Property(e => e.DateFacture).HasColumnName("date_facture");
            });
            modelBuilder.Entity<MB_ART>(entity =>
            {
                entity.ToTable("MB_ART"); // Nom de la table

                entity.HasNoKey();
                
                entity.Property(e => e.AR_Ref);
                      

                entity.Property(e => e.AR_SuiviStock);
                entity.Property(e => e.LS_NoSerie);
                entity.Property(e => e.LS_Peremption);
                entity.Property(e => e.AR_Design);
                entity.Property(e => e.AR_PUNet);
                entity.Property(e => e.TypeSuivi).HasColumnName("Type Suivi");
                entity.Property(e => e.AR_CodeBarre);
            });
            modelBuilder.Entity<Commande>(entity =>
            {
                entity.ToTable("Commande");
                entity.HasKey(c => c.Id);
                entity.Property(e => e.DatePeremtion).HasColumnName("DatePérumption");
                entity.Property(e => e.NumSerie).HasColumnName("NumSérie");
                entity.Property(e => e.DatePeremtion1).HasColumnName("DatePérumption1");
                entity.Property(e => e.NumSerie1).HasColumnName("NumSérie1");
                entity.Property(e => e.DatePeremtion2).HasColumnName("DatePérumption2");
                entity.Property(e => e.NumSerie2).HasColumnName("NumSérie2");
                entity.Property(e => e.Qte1).HasColumnName("Qte1");
                entity.Property(e => e.Qte2).HasColumnName("Qte2");
                entity.Property(e => e.Qte3).HasColumnName("Qte3");
            });

            modelBuilder.Entity<LoginRequest>(entity =>
            {
                entity.ToTable("Authentication");

            });
            modelBuilder.Entity<DetailArticle>(entity =>
            {
                entity.ToTable("DetailArticle");

            });

            modelBuilder.Entity<F_Article>(entity =>
            {
                entity.HasKey(e => e.ArRef);
                entity.ToTable("F_ARTICLE");
                entity.Property(e => e.Recommande)
                      .HasColumnName("Recommandé");
                entity.Property(e => e.ArRef)
               .HasColumnName("AR_Ref");

            });
            modelBuilder.Entity<F_Famille>(entity =>
            {
                entity.HasNoKey();
                entity.ToTable("F_Famille");


            });
            modelBuilder.Entity<MbArticle>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MB_ARTICLE");

                entity.Property(e => e.AfRefFourniss)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AF_RefFourniss");
                entity.Property(e => e.ArDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("AR_Design");

                entity.Property(e => e.ArPrixAch)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PrixAch");

                entity.Property(e => e.ArPrixVen)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PrixVen");

                entity.Property(e => e.ArPunet)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PUNet");

                entity.Property(e => e.ArRef)
                    .IsRequired()
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.AsQteMaxi)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AS_QteMaxi");

                entity.Property(e => e.AsQteMini)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AS_QteMini");

                entity.Property(e => e.AsQteRes)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AS_QteRes");

                entity.Property(e => e.AsQteSto)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AS_QteSto");

                entity.Property(e => e.CtIntitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Intitule");

                entity.Property(e => e.CtNum)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Num");

                entity.Property(e => e.DeNo).HasColumnName("DE_No");

                entity.Property(e => e.FaCodeFamille)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("FA_CodeFamille");

                entity.Property(e => e.Marque)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AR_CodeBarre)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasColumnName("AR_CodeBarre");

            });

            modelBuilder.Entity<MbDocligne>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MB_DOCLIGNE");

                entity.Property(e => e.AcRefClient)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AC_RefClient");

                entity.Property(e => e.AfRefFourniss)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AF_RefFourniss");

                entity.Property(e => e.AgNo1).HasColumnName("AG_No1");

                entity.Property(e => e.AgNo2).HasColumnName("AG_No2");

                entity.Property(e => e.ArRef)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.ArRefCompose)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_RefCompose");

                entity.Property(e => e.Ca)
                    .HasColumnType("numeric(38, 6)")
                    .HasColumnName("CA");

                entity.Property(e => e.CaNo).HasColumnName("CA_No");

                entity.Property(e => e.CaNum)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("CA_Num");

                entity.Property(e => e.CbAfRefFourniss)
                    .HasMaxLength(20)
                    .HasColumnName("cbAF_RefFourniss");

                entity.Property(e => e.CbArRef)
                    .HasMaxLength(20)
                    .HasColumnName("cbAR_Ref");

                entity.Property(e => e.CbArRefCompose)
                    .HasMaxLength(20)
                    .HasColumnName("cbAR_RefCompose");

                entity.Property(e => e.CbCaNo).HasColumnName("cbCA_No");

                entity.Property(e => e.CbCaNum)
                    .HasMaxLength(14)
                    .HasColumnName("cbCA_Num");

                entity.Property(e => e.CbCoNo).HasColumnName("cbCO_No");

                entity.Property(e => e.CbCreateur)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("cbCreateur")
                    .IsFixedLength();

                entity.Property(e => e.CbCreation)
                    .HasColumnType("datetime")
                    .HasColumnName("cbCreation");

                entity.Property(e => e.CbCreationUser).HasColumnName("cbCreationUser");

                entity.Property(e => e.CbCtNum)
                    .HasMaxLength(18)
                    .HasColumnName("cbCT_Num");

                entity.Property(e => e.CbDeNo).HasColumnName("cbDE_No");

                entity.Property(e => e.CbDlNoLink).HasColumnName("cbDL_NoLink");

                entity.Property(e => e.CbDlPieceBc)
                    .HasMaxLength(14)
                    .HasColumnName("cbDL_PieceBC");

                entity.Property(e => e.CbDlPieceBl)
                    .HasMaxLength(14)
                    .HasColumnName("cbDL_PieceBL");

                entity.Property(e => e.CbDlPieceDe)
                    .HasMaxLength(14)
                    .HasColumnName("cbDL_PieceDE");

                entity.Property(e => e.CbDlPiecePl)
                    .HasMaxLength(14)
                    .HasColumnName("cbDL_PiecePL");

                entity.Property(e => e.CbDoPiece)
                    .HasMaxLength(14)
                    .HasColumnName("cbDO_Piece");

                entity.Property(e => e.CbDoRef)
                    .HasMaxLength(18)
                    .HasColumnName("cbDO_Ref");

                entity.Property(e => e.CbDtNo).HasColumnName("cbDT_No");

                entity.Property(e => e.CbFlag).HasColumnName("cbFlag");

                entity.Property(e => e.CbHash)
                    .HasMaxLength(32)
                    .HasColumnName("cbHash");

                entity.Property(e => e.CbHashDate)
                    .HasColumnType("datetime")
                    .HasColumnName("cbHashDate");

                entity.Property(e => e.CbHashOrder).HasColumnName("cbHashOrder");

                entity.Property(e => e.CbHashVersion).HasColumnName("cbHashVersion");

                entity.Property(e => e.CbMarq).HasColumnName("cbMarq");

                entity.Property(e => e.CbModification)
                    .HasColumnType("datetime")
                    .HasColumnName("cbModification");

                entity.Property(e => e.CbPfNum)
                    .HasMaxLength(10)
                    .HasColumnName("cbPF_Num");

                entity.Property(e => e.CbProt).HasColumnName("cbProt");

                entity.Property(e => e.CbReplication).HasColumnName("cbReplication");

                entity.Property(e => e.CbRpCode)
                    .HasMaxLength(12)
                    .HasColumnName("cbRP_Code");

                entity.Property(e => e.CoNo).HasColumnName("CO_No");

                entity.Property(e => e.CtNum)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Num");

                entity.Property(e => e.DeNo).HasColumnName("DE_No");

                entity.Property(e => e.DlCmup)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_CMUP");

                entity.Property(e => e.DlCodeTaxe1)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("DL_CodeTaxe1");

                entity.Property(e => e.DlCodeTaxe2)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("DL_CodeTaxe2");

                entity.Property(e => e.DlCodeTaxe3)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("DL_CodeTaxe3");

                entity.Property(e => e.DlDateAvancement)
                    .HasColumnType("datetime")
                    .HasColumnName("DL_DateAvancement");

                entity.Property(e => e.DlDateBc)
                    .HasColumnType("datetime")
                    .HasColumnName("DL_DateBC");

                entity.Property(e => e.DlDateBl)
                    .HasColumnType("datetime")
                    .HasColumnName("DL_DateBL");

                entity.Property(e => e.DlDateDe)
                    .HasColumnType("datetime")
                    .HasColumnName("DL_DateDE");

                entity.Property(e => e.DlDatePl)
                    .HasColumnType("datetime")
                    .HasColumnName("DL_DatePL");

                entity.Property(e => e.DlDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("DL_Design");

                entity.Property(e => e.DlEscompte).HasColumnName("DL_Escompte");

                entity.Property(e => e.DlFactPoids).HasColumnName("DL_FactPoids");

                entity.Property(e => e.DlFrais)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Frais");

                entity.Property(e => e.DlLigne).HasColumnName("DL_Ligne");

                entity.Property(e => e.DlMontantHt)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_MontantHT");

                entity.Property(e => e.DlMontantTtc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_MontantTTC");

                entity.Property(e => e.DlMvtStock).HasColumnName("DL_MvtStock");

                entity.Property(e => e.DlNo).HasColumnName("DL_No");

                entity.Property(e => e.DlNoColis)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("DL_NoColis");

                entity.Property(e => e.DlNoLink).HasColumnName("DL_NoLink");

                entity.Property(e => e.DlNoRef).HasColumnName("DL_NoRef");

                entity.Property(e => e.DlNoSousTotal).HasColumnName("DL_NoSousTotal");

                entity.Property(e => e.DlNonLivre).HasColumnName("DL_NonLivre");

                entity.Property(e => e.DlOperation)
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("DL_Operation");

                entity.Property(e => e.DlPieceBc)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DL_PieceBC");

                entity.Property(e => e.DlPieceBl)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DL_PieceBL");

                entity.Property(e => e.DlPieceDe)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DL_PieceDE");

                entity.Property(e => e.DlPieceOfprod).HasColumnName("DL_PieceOFProd");

                entity.Property(e => e.DlPiecePl)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DL_PiecePL");

                entity.Property(e => e.DlPoidsBrut)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PoidsBrut");

                entity.Property(e => e.DlPoidsNet)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PoidsNet");

                entity.Property(e => e.DlPrixRu)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PrixRU");

                entity.Property(e => e.DlPrixUnitaire)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PrixUnitaire");

                entity.Property(e => e.DlPubc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PUBC");

                entity.Property(e => e.DlPudevise)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PUDevise");

                entity.Property(e => e.DlPuttc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PUTTC");

                entity.Property(e => e.DlQte)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Qte");

                entity.Property(e => e.DlQteBc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QteBC");

                entity.Property(e => e.DlQteBl)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QteBL");

                entity.Property(e => e.DlQteDe)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QteDE");

                entity.Property(e => e.DlQtePl)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QtePL");

                entity.Property(e => e.DlQteRessource).HasColumnName("DL_QteRessource");

                entity.Property(e => e.DlRemise01RemType).HasColumnName("DL_Remise01REM_Type");

                entity.Property(e => e.DlRemise01RemValeur)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Remise01REM_Valeur");

                entity.Property(e => e.DlRemise02RemType).HasColumnName("DL_Remise02REM_Type");

                entity.Property(e => e.DlRemise02RemValeur)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Remise02REM_Valeur");

                entity.Property(e => e.DlRemise03RemType).HasColumnName("DL_Remise03REM_Type");

                entity.Property(e => e.DlRemise03RemValeur)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Remise03REM_Valeur");

                entity.Property(e => e.DlTaxe1)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Taxe1");

                entity.Property(e => e.DlTaxe2)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Taxe2");

                entity.Property(e => e.DlTaxe3)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Taxe3");

                entity.Property(e => e.DlTnomencl).HasColumnName("DL_TNomencl");

                entity.Property(e => e.DlTremExep).HasColumnName("DL_TRemExep");

                entity.Property(e => e.DlTremPied).HasColumnName("DL_TRemPied");

                entity.Property(e => e.DlTtc).HasColumnName("DL_TTC");

                entity.Property(e => e.DlTypePl).HasColumnName("DL_TypePL");

                entity.Property(e => e.DlTypeTaux1).HasColumnName("DL_TypeTaux1");

                entity.Property(e => e.DlTypeTaux2).HasColumnName("DL_TypeTaux2");

                entity.Property(e => e.DlTypeTaux3).HasColumnName("DL_TypeTaux3");

                entity.Property(e => e.DlTypeTaxe1).HasColumnName("DL_TypeTaxe1");

                entity.Property(e => e.DlTypeTaxe2).HasColumnName("DL_TypeTaxe2");

                entity.Property(e => e.DlTypeTaxe3).HasColumnName("DL_TypeTaxe3");

                entity.Property(e => e.DlValorise).HasColumnName("DL_Valorise");

                entity.Property(e => e.DoDate)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_Date");

                entity.Property(e => e.DoDateLivr)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_DateLivr");

                entity.Property(e => e.DoDocType).HasColumnName("DO_DocType");

                entity.Property(e => e.DoDomaine).HasColumnName("DO_Domaine");

                entity.Property(e => e.DoPiece)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DO_Piece");

                entity.Property(e => e.DoRef)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_Ref");

                entity.Property(e => e.DoType).HasColumnName("DO_Type");

                entity.Property(e => e.DtNo).HasColumnName("DT_No");

                entity.Property(e => e.EuEnumere)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("EU_Enumere");

                entity.Property(e => e.EuQte)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("EU_Qte");

                entity.Property(e => e.PfNum)
                    .IsRequired()
                    .HasMaxLength(9)
                    .IsUnicode(false)
                    .HasColumnName("PF_Num");

                entity.Property(e => e.Qtevendue)
                    .HasColumnType("numeric(38, 6)")
                    .HasColumnName("QTEVENDUE");

                entity.Property(e => e.RpCode)
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("RP_Code");

                entity.Property(e => e.Utilisateur)
                    .HasMaxLength(69)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<MbMouv>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MB _MOUV");

                entity.Property(e => e.ArRef)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.CoNo).HasColumnName("CO_No");

                entity.Property(e => e.CtIntitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Intitule");

                entity.Property(e => e.CtNumPayeur)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_NumPayeur");

                entity.Property(e => e.Depot).HasColumnName("DEPOT");

                entity.Property(e => e.DlCmup)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_CMUP");

                entity.Property(e => e.DlPrixRu)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PrixRU");

                entity.Property(e => e.DlPrixUnitaire)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PrixUnitaire");

                entity.Property(e => e.DlPuttc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PUTTC");

                entity.Property(e => e.DlQte)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Qte");

                entity.Property(e => e.DlQteBc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QteBC");

                entity.Property(e => e.DlQteBl)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QteBL");

                entity.Property(e => e.DlQteDe)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QteDE");

                entity.Property(e => e.DlQtePl)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QtePL");

                entity.Property(e => e.DoDate)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_Date");

                entity.Property(e => e.DoDevise).HasColumnName("DO_Devise");

                entity.Property(e => e.DoDomaine).HasColumnName("DO_Domaine");

                entity.Property(e => e.DoMontantRegle)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_MontantRegle");

                entity.Property(e => e.DoNetApayer)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_NetAPayer");

                entity.Property(e => e.DoPiece)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DO_Piece");

                entity.Property(e => e.DoRef)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_Ref");

                entity.Property(e => e.DoTiers)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_Tiers");

                entity.Property(e => e.DoTotalHt)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalHT");

                entity.Property(e => e.DoTotalHtnet)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalHTNet");

                entity.Property(e => e.DoTotalTtc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalTTC");

                entity.Property(e => e.DoType).HasColumnName("DO_Type");

                entity.Property(e => e.EuQte)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("EU_Qte");

                entity.Property(e => e.HtLigne)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("HT LIGNE");

                entity.Property(e => e.TtcLigne)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("TTC LIGNE");
            });

            modelBuilder.Entity<MsAArticle>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_ARTICLE");

                entity.Property(e => e.ArDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("AR_Design");

                entity.Property(e => e.ArPrixAch)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PrixAch");


                entity.Property(e => e.ArPrixVen)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PrixVen");

                entity.Property(e => e.Nouveaute)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("Nouveauté");
                entity.Property(e => e.ArPublie).HasColumnName("AR_Publie");

                entity.Property(e => e.Recommande)
                .HasColumnName("Recommandé");
                entity.Property(e => e.AR_CodeBarre);

                entity.Property(e => e.ArPunet)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PUNet");

                entity.Property(e => e.ArRef)
                    .IsRequired()
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");
                entity.Property(e => e.Description)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("Description");
                entity.Property(e => e.C_Utilisation)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("C_Utilisation");
                entity.Property(e => e.Composition)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("Composition");
                entity.Property(e => e.FaCodeFamille)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("FA_CodeFamille");

                entity.Property(e => e.Marque)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AR_CodeBarre)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasColumnName("AR_CodeBarre");


            });

            modelBuilder.Entity<MsAArticleCommercial>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_ARTICLE_COMMERCIAL");

                entity.Property(e => e.ArDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("AR_Design");

                entity.Property(e => e.ArRef)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.Client)
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasColumnName("CLIENT");

                entity.Property(e => e.Collaborateur)
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasColumnName("COLLABORATEUR");

                entity.Property(e => e.Commercial)
                    .HasMaxLength(300)
                    .IsUnicode(false)
                    .HasColumnName("COMMERCIAL");

                entity.Property(e => e.CtIntitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Intitule");

                entity.Property(e => e.FaCodeFamille)
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("FA_CodeFamille");

                entity.Property(e => e.Flag)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Prenomcoll)
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasColumnName("PRENOMCOLL");

                entity.Property(e => e.Type)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("type");
            });

            modelBuilder.Entity<MsAArticles>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_ARTICLES");

                entity.Property(e => e.ArDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("AR_Design");

                entity.Property(e => e.ArPrixTtc).HasColumnName("AR_PrixTTC");

                entity.Property(e => e.ArPrixVen)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("AR_PrixVen");

                entity.Property(e => e.ArRef)
                    .IsRequired()
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.CbMarq).HasColumnName("cbMarq");

                entity.Property(e => e.CtIntitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Intitule");

                entity.Property(e => e.FaCodeFamille)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("FA_CodeFamille");
            });

            modelBuilder.Entity<MsAClients>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_CLIENTS");

                entity.Property(e => e.CbMarq).HasColumnName("cbMarq");

                //entity.Property(e => e.Collaborateur)
                //    .HasMaxLength(150)
                //    .IsUnicode(false)
                //    .HasColumnName("COLLABORATEUR");

                entity.Property(e => e.CtAdresse)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Adresse");

                entity.Property(e => e.CtClassement)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Classement");

                entity.Property(e => e.CtCodePostal)
                    .HasMaxLength(9)
                    .IsUnicode(false)
                    .HasColumnName("CT_CodePostal");

                entity.Property(e => e.CtCodeRegion)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("CT_CodeRegion");

                entity.Property(e => e.CtComplement)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Complement");

                entity.Property(e => e.CtContact)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Contact");

                entity.Property(e => e.CtEmail)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_EMail");

                entity.Property(e => e.CtIdentifiant)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("CT_Identifiant");

                entity.Property(e => e.CtIntitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Intitule");

                entity.Property(e => e.CtNum)
                    .IsRequired()
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Num");

                entity.Property(e => e.CtPays)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Pays");

                entity.Property(e => e.CtQualite)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Qualite");

                entity.Property(e => e.CtSiret)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("CT_Siret");

                entity.Property(e => e.CtSite)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Site");

                entity.Property(e => e.CtSommeil).HasColumnName("CT_Sommeil");

                entity.Property(e => e.CtTelephone)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Telephone");

                entity.Property(e => e.CtType).HasColumnName("CT_Type");

                entity.Property(e => e.CtVille)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Ville");

                entity.Property(e => e.NCatTarif).HasColumnName("N_CatTarif");

                //entity.Property(e => e.Prenomcoll)
                //    .HasMaxLength(150)
                //    .IsUnicode(false)
                //    .HasColumnName("PRENOMCOLL");
            });

            modelBuilder.Entity<MsAEntt>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_ENTT");

                entity.Property(e => e.CbMarq)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("cbMarq");

                entity.Property(e => e.Destinataire)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("DESTINATAIRE");

                entity.Property(e => e.Destination)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("DESTINATION");

                entity.Property(e => e.DoDate)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_Date");

                entity.Property(e => e.DoDomaine).HasColumnName("DO_Domaine");

                entity.Property(e => e.DoPiece)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DO_Piece");

                entity.Property(e => e.DoTiers)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_Tiers");
                entity.Property(e => e.DoTotalHtnet)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalHTNet");
                entity.Property(e => e.DoMontantRegle)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_MontantRegle");
                entity.Property(e => e.DoNetAPayer)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_NetAPayer");
                entity.Property(e => e.DoTotalTtc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalTTC");

                entity.Property(e => e.DoType).HasColumnName("DO_Type");

                entity.Property(e => e.Marque)
                    .HasMaxLength(35)
                    .IsUnicode(false);

                entity.Property(e => e.Type)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("TYPE");
            });

            modelBuilder.Entity<MsALigne>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_LIGNE");

                entity.Property(e => e.ArRef)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.CbMarq)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("cbMarq");

                entity.Property(e => e.DlDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("DL_Design");

                entity.Property(e => e.DlMontantHt)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_MontantHT");

                entity.Property(e => e.DlMontantTtc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_MontantTTC");

                entity.Property(e => e.DlPrixUnitaire)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PrixUnitaire");

                entity.Property(e => e.DlPudevise)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PUDevise");

                entity.Property(e => e.DlPuttc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_PUTTC");

                entity.Property(e => e.DlQte)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Qte");

                entity.Property(e => e.DlQteBc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_QteBC");

                entity.Property(e => e.DoDate)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_Date");

                entity.Property(e => e.DoDomaine).HasColumnName("DO_Domaine");

                entity.Property(e => e.DoPiece)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DO_Piece");

                entity.Property(e => e.DoRef)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_Ref");

                entity.Property(e => e.DoType).HasColumnName("DO_Type");

                entity.Property(e => e.Utilisateur)
                    .HasMaxLength(69)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<MsAMarques>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_MARQUES");

                entity.Property(e => e.BtNum).HasColumnName("BT_Num");

                entity.Property(e => e.CaNum)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("CA_Num");

                entity.Property(e => e.CaNumIfrs)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("CA_NumIFRS");

                entity.Property(e => e.CalNo).HasColumnName("CAL_No");

                entity.Property(e => e.CbCaNum)
                    .HasMaxLength(14)
                    .HasColumnName("cbCA_Num");

                entity.Property(e => e.CbCalNo).HasColumnName("cbCAL_No");

                entity.Property(e => e.CbCgNumPrinc)
                    .HasMaxLength(14)
                    .HasColumnName("cbCG_NumPrinc");

                entity.Property(e => e.CbCoNo).HasColumnName("cbCO_No");

                entity.Property(e => e.CbCreateur)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("cbCreateur")
                    .IsFixedLength();

                entity.Property(e => e.CbCreation)
                    .HasColumnType("datetime")
                    .HasColumnName("cbCreation");

                entity.Property(e => e.CbCreationUser).HasColumnName("cbCreationUser");

                entity.Property(e => e.CbCtClassement)
                    .HasMaxLength(18)
                    .HasColumnName("cbCT_Classement");

                entity.Property(e => e.CbCtCodePostal)
                    .HasMaxLength(10)
                    .HasColumnName("cbCT_CodePostal");

                entity.Property(e => e.CbCtNum)
                    .HasMaxLength(18)
                    .HasColumnName("cbCT_Num");

                entity.Property(e => e.CbCtNumCentrale)
                    .HasMaxLength(18)
                    .HasColumnName("cbCT_NumCentrale");

                entity.Property(e => e.CbCtNumPayeur)
                    .HasMaxLength(18)
                    .HasColumnName("cbCT_NumPayeur");

                entity.Property(e => e.CbCtRaccourci)
                    .HasMaxLength(8)
                    .HasColumnName("cbCT_Raccourci");

                entity.Property(e => e.CbDeNo).HasColumnName("cbDE_No");

                entity.Property(e => e.CbEbNo).HasColumnName("cbEB_No");

                entity.Property(e => e.CbFlag).HasColumnName("cbFlag");

                entity.Property(e => e.CbMarq).HasColumnName("cbMarq");

                entity.Property(e => e.CbModification)
                    .HasColumnType("datetime")
                    .HasColumnName("cbModification");

                entity.Property(e => e.CbMrNo).HasColumnName("cbMR_No");

                entity.Property(e => e.CbNAnalytique).HasColumnName("cbN_Analytique");

                entity.Property(e => e.CbNAnalytiqueIfrs).HasColumnName("cbN_AnalytiqueIFRS");

                entity.Property(e => e.CbPiNoEchange).HasColumnName("cbPI_NoEchange");

                entity.Property(e => e.CbProt).HasColumnName("cbProt");

                entity.Property(e => e.CbReplication).HasColumnName("cbReplication");

                entity.Property(e => e.CgNumPrinc)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("CG_NumPrinc");

                entity.Property(e => e.CoNo).HasColumnName("CO_No");

                entity.Property(e => e.CtAdresse)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Adresse");

                entity.Property(e => e.CtAnnulationCr).HasColumnName("CT_AnnulationCR");

                entity.Property(e => e.CtApe)
                    .HasMaxLength(7)
                    .IsUnicode(false)
                    .HasColumnName("CT_Ape");

                entity.Property(e => e.CtAssurance)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_Assurance");

                entity.Property(e => e.CtBlfact).HasColumnName("CT_BLFact");

                entity.Property(e => e.CtBonApayer).HasColumnName("CT_BonAPayer");

                entity.Property(e => e.CtClassement)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Classement");

                entity.Property(e => e.CtCodePostal)
                    .HasMaxLength(9)
                    .IsUnicode(false)
                    .HasColumnName("CT_CodePostal");

                entity.Property(e => e.CtCodeRegion)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("CT_CodeRegion");

                entity.Property(e => e.CtCoface)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("CT_Coface");

                entity.Property(e => e.CtCommentaire)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Commentaire");

                entity.Property(e => e.CtComplement)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Complement");

                entity.Property(e => e.CtContact)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Contact");

                entity.Property(e => e.CtControlEnc).HasColumnName("CT_ControlEnc");

                entity.Property(e => e.CtDateFermeDebut)
                    .HasColumnType("datetime")
                    .HasColumnName("CT_DateFermeDebut");

                entity.Property(e => e.CtDateFermeFin)
                    .HasColumnType("datetime")
                    .HasColumnName("CT_DateFermeFin");

                entity.Property(e => e.CtDateMaj)
                    .HasColumnType("datetime")
                    .HasColumnName("CT_DateMAJ");

                entity.Property(e => e.CtDelaiAppro).HasColumnName("CT_DelaiAppro");

                entity.Property(e => e.CtDelaiTransport).HasColumnName("CT_DelaiTransport");

                entity.Property(e => e.CtDeliveryDay01).HasColumnName("CT_DeliveryDay01");

                entity.Property(e => e.CtDeliveryDay02).HasColumnName("CT_DeliveryDay02");

                entity.Property(e => e.CtDeliveryDay03).HasColumnName("CT_DeliveryDay03");

                entity.Property(e => e.CtDeliveryDay04).HasColumnName("CT_DeliveryDay04");

                entity.Property(e => e.CtDeliveryDay05).HasColumnName("CT_DeliveryDay05");

                entity.Property(e => e.CtDeliveryDay06).HasColumnName("CT_DeliveryDay06");

                entity.Property(e => e.CtDeliveryDay07).HasColumnName("CT_DeliveryDay07");

                entity.Property(e => e.CtEchangeCr).HasColumnName("CT_EchangeCR");

                entity.Property(e => e.CtEchangeRappro).HasColumnName("CT_EchangeRappro");

                entity.Property(e => e.CtEdiCode)
                    .HasMaxLength(23)
                    .IsUnicode(false)
                    .HasColumnName("CT_EdiCode");

                entity.Property(e => e.CtEdiCodeSage)
                    .HasMaxLength(9)
                    .IsUnicode(false)
                    .HasColumnName("CT_EdiCodeSage");

                entity.Property(e => e.CtEdiCodeType).HasColumnName("CT_EdiCodeType");

                entity.Property(e => e.CtEmail)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_EMail");

                entity.Property(e => e.CtEncours)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_Encours");

                entity.Property(e => e.CtExclureTrait).HasColumnName("CT_ExclureTrait");

                entity.Property(e => e.CtFacebook)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Facebook");

                entity.Property(e => e.CtFacture).HasColumnName("CT_Facture");

                entity.Property(e => e.CtFactureElec).HasColumnName("CT_FactureElec");

                entity.Property(e => e.CtGdpr).HasColumnName("CT_GDPR");

                entity.Property(e => e.CtIdentifiant)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("CT_Identifiant");

                entity.Property(e => e.CtIntitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Intitule");

                entity.Property(e => e.CtLangue).HasColumnName("CT_Langue");

                entity.Property(e => e.CtLangueIso2)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("CT_LangueISO2");

                entity.Property(e => e.CtLettrage).HasColumnName("CT_Lettrage");

                entity.Property(e => e.CtLinkedIn)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_LinkedIn");

                entity.Property(e => e.CtLivrPartielle).HasColumnName("CT_LivrPartielle");

                entity.Property(e => e.CtNotPenal).HasColumnName("CT_NotPenal");

                entity.Property(e => e.CtNotRappel).HasColumnName("CT_NotRappel");

                entity.Property(e => e.CtNum)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Num");

                entity.Property(e => e.CtNumCentrale)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_NumCentrale");

                entity.Property(e => e.CtNumPayeur)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_NumPayeur");

                entity.Property(e => e.CtOrderDay01).HasColumnName("CT_OrderDay01");

                entity.Property(e => e.CtOrderDay02).HasColumnName("CT_OrderDay02");

                entity.Property(e => e.CtOrderDay03).HasColumnName("CT_OrderDay03");

                entity.Property(e => e.CtOrderDay04).HasColumnName("CT_OrderDay04");

                entity.Property(e => e.CtOrderDay05).HasColumnName("CT_OrderDay05");

                entity.Property(e => e.CtOrderDay06).HasColumnName("CT_OrderDay06");

                entity.Property(e => e.CtOrderDay07).HasColumnName("CT_OrderDay07");

                entity.Property(e => e.CtPays)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Pays");

                entity.Property(e => e.CtPrioriteLivr).HasColumnName("CT_PrioriteLivr");

                entity.Property(e => e.CtProfilSoc).HasColumnName("CT_ProfilSoc");

                entity.Property(e => e.CtProspect).HasColumnName("CT_Prospect");

                entity.Property(e => e.CtQualite)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Qualite");

                entity.Property(e => e.CtRaccourci)
                    .HasMaxLength(7)
                    .IsUnicode(false)
                    .HasColumnName("CT_Raccourci");

                entity.Property(e => e.CtRepresentInt)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_RepresentInt");

                entity.Property(e => e.CtRepresentNif)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("CT_RepresentNIF");

                entity.Property(e => e.CtSaut).HasColumnName("CT_Saut");

                entity.Property(e => e.CtSiret)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("CT_Siret");

                entity.Property(e => e.CtSite)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Site");

                entity.Property(e => e.CtSommeil).HasColumnName("CT_Sommeil");

                entity.Property(e => e.CtStatistique01)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique01");

                entity.Property(e => e.CtStatistique02)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique02");

                entity.Property(e => e.CtStatistique03)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique03");

                entity.Property(e => e.CtStatistique04)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique04");

                entity.Property(e => e.CtStatistique05)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique05");

                entity.Property(e => e.CtStatistique06)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique06");

                entity.Property(e => e.CtStatistique07)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique07");

                entity.Property(e => e.CtStatistique08)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique08");

                entity.Property(e => e.CtStatistique09)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique09");

                entity.Property(e => e.CtStatistique10)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Statistique10");

                entity.Property(e => e.CtStatutContrat).HasColumnName("CT_StatutContrat");

                entity.Property(e => e.CtSurveillance).HasColumnName("CT_Surveillance");

                entity.Property(e => e.CtSvCa)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_SvCA");

                entity.Property(e => e.CtSvCotation)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("CT_SvCotation");

                entity.Property(e => e.CtSvDateBilan)
                    .HasColumnType("datetime")
                    .HasColumnName("CT_SvDateBilan");

                entity.Property(e => e.CtSvDateCreate)
                    .HasColumnType("datetime")
                    .HasColumnName("CT_SvDateCreate");

                entity.Property(e => e.CtSvDateIncid)
                    .HasColumnType("datetime")
                    .HasColumnName("CT_SvDateIncid");

                entity.Property(e => e.CtSvDateMaj)
                    .HasColumnType("datetime")
                    .HasColumnName("CT_SvDateMaj");

                entity.Property(e => e.CtSvEffectif)
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("CT_SvEffectif");

                entity.Property(e => e.CtSvFormeJuri)
                    .HasMaxLength(33)
                    .IsUnicode(false)
                    .HasColumnName("CT_SvFormeJuri");

                entity.Property(e => e.CtSvIncident).HasColumnName("CT_SvIncident");

                entity.Property(e => e.CtSvNbMoisBilan).HasColumnName("CT_SvNbMoisBilan");

                entity.Property(e => e.CtSvObjetMaj)
                    .HasMaxLength(61)
                    .IsUnicode(false)
                    .HasColumnName("CT_SvObjetMaj");

                entity.Property(e => e.CtSvPrivil).HasColumnName("CT_SvPrivil");

                entity.Property(e => e.CtSvRegul)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("CT_SvRegul");

                entity.Property(e => e.CtSvResultat)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_SvResultat");

                entity.Property(e => e.CtTaux01)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_Taux01");

                entity.Property(e => e.CtTaux02)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_Taux02");

                entity.Property(e => e.CtTaux03)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_Taux03");

                entity.Property(e => e.CtTaux04)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("CT_Taux04");

                entity.Property(e => e.CtTelecopie)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Telecopie");

                entity.Property(e => e.CtTelephone)
                    .HasMaxLength(21)
                    .IsUnicode(false)
                    .HasColumnName("CT_Telephone");

                entity.Property(e => e.CtType).HasColumnName("CT_Type");

                entity.Property(e => e.CtTypeNif).HasColumnName("CT_TypeNIF");

                entity.Property(e => e.CtValidEch).HasColumnName("CT_ValidEch");

                entity.Property(e => e.CtVille)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CT_Ville");

                entity.Property(e => e.DeNo).HasColumnName("DE_No");

                entity.Property(e => e.EbNo).HasColumnName("EB_No");

                entity.Property(e => e.Expr1)
                    .HasMaxLength(69)
                    .IsUnicode(false);

                entity.Property(e => e.Expr2)
                    .HasMaxLength(17)
                    .IsUnicode(false);

                entity.Property(e => e.MrNo).HasColumnName("MR_No");

                entity.Property(e => e.NAnalytique).HasColumnName("N_Analytique");

                entity.Property(e => e.NAnalytiqueIfrs).HasColumnName("N_AnalytiqueIFRS");

                entity.Property(e => e.NCatCompta).HasColumnName("N_CatCompta");

                entity.Property(e => e.NCatTarif).HasColumnName("N_CatTarif");

                entity.Property(e => e.NCondition).HasColumnName("N_Condition");

                entity.Property(e => e.NDevise).HasColumnName("N_Devise");

                entity.Property(e => e.NExpedition).HasColumnName("N_Expedition");

                entity.Property(e => e.NPeriod).HasColumnName("N_Period");

                entity.Property(e => e.NRisque).HasColumnName("N_Risque");

                entity.Property(e => e.PiNoEchange).HasColumnName("PI_NoEchange");
            });

            modelBuilder.Entity<MsAPiece>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_PIECE");

                entity.Property(e => e.AbNo).HasColumnName("AB_No");

                entity.Property(e => e.CaNo).HasColumnName("CA_No");

                entity.Property(e => e.CaNum)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("CA_Num");

                entity.Property(e => e.CaNumIfrs)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("CA_NumIFRS");

                entity.Property(e => e.CbCaNo).HasColumnName("cbCA_No");

                entity.Property(e => e.CbCaNum)
                    .HasMaxLength(14)
                    .HasColumnName("cbCA_Num");

                entity.Property(e => e.CbCgNum)
                    .HasMaxLength(14)
                    .HasColumnName("cbCG_Num");

                entity.Property(e => e.CbCoNo).HasColumnName("cbCO_No");

                entity.Property(e => e.CbCoNoCaissier).HasColumnName("cbCO_NoCaissier");

                entity.Property(e => e.CbCreateur)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("cbCreateur")
                    .IsFixedLength();

                entity.Property(e => e.CbCreation)
                    .HasColumnType("datetime")
                    .HasColumnName("cbCreation");

                entity.Property(e => e.CbCreationUser).HasColumnName("cbCreationUser");

                entity.Property(e => e.CbCtNumCentrale)
                    .HasMaxLength(18)
                    .HasColumnName("cbCT_NumCentrale");

                entity.Property(e => e.CbCtNumPayeur)
                    .HasMaxLength(18)
                    .HasColumnName("cbCT_NumPayeur");

                entity.Property(e => e.CbDeNo).HasColumnName("cbDE_No");

                entity.Property(e => e.CbDoFactureFrs)
                    .HasMaxLength(36)
                    .HasColumnName("cbDO_FactureFrs");

                entity.Property(e => e.CbDoPiece)
                    .HasMaxLength(14)
                    .HasColumnName("cbDO_Piece");

                entity.Property(e => e.CbDoPieceOrig)
                    .HasMaxLength(14)
                    .HasColumnName("cbDO_PieceOrig");

                entity.Property(e => e.CbDoTiers)
                    .HasMaxLength(18)
                    .HasColumnName("cbDO_Tiers");

                entity.Property(e => e.CbEtNo).HasColumnName("cbET_No");

                entity.Property(e => e.CbFlag).HasColumnName("cbFlag");

                entity.Property(e => e.CbHash)
                    .HasMaxLength(32)
                    .HasColumnName("cbHash");

                entity.Property(e => e.CbHashDate)
                    .HasColumnType("datetime")
                    .HasColumnName("cbHashDate");

                entity.Property(e => e.CbHashOrder).HasColumnName("cbHashOrder");

                entity.Property(e => e.CbHashVersion).HasColumnName("cbHashVersion");

                entity.Property(e => e.CbLiNo).HasColumnName("cbLI_No");

                entity.Property(e => e.CbMarq).HasColumnName("cbMarq");

                entity.Property(e => e.CbModification)
                    .HasColumnType("datetime")
                    .HasColumnName("cbModification");

                entity.Property(e => e.CbProt).HasColumnName("cbProt");

                entity.Property(e => e.CbReplication).HasColumnName("cbReplication");

                entity.Property(e => e.CgNum)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("CG_Num");

                entity.Property(e => e.CoNo).HasColumnName("CO_No");

                entity.Property(e => e.CoNoCaissier).HasColumnName("CO_NoCaissier");

                entity.Property(e => e.CoNom)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CO_Nom");

                entity.Property(e => e.CoPrenom)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CO_Prenom");

                entity.Property(e => e.CtNumCentrale)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_NumCentrale");

                entity.Property(e => e.CtNumPayeur)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_NumPayeur");

                entity.Property(e => e.DeNo).HasColumnName("DE_No");

                entity.Property(e => e.Destinataire)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("DESTINATAIRE");

                entity.Property(e => e.Destination)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("DESTINATION");

                entity.Property(e => e.DoAdressePaiement)
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("DO_AdressePaiement");

                entity.Property(e => e.DoAttente).HasColumnName("DO_Attente");

                entity.Property(e => e.DoBlfact).HasColumnName("DO_BLFact");

                entity.Property(e => e.DoCloture).HasColumnName("DO_Cloture");

                entity.Property(e => e.DoCodeTaxe1)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("DO_CodeTaxe1");

                entity.Property(e => e.DoCodeTaxe2)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("DO_CodeTaxe2");

                entity.Property(e => e.DoCodeTaxe3)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("DO_CodeTaxe3");

                entity.Property(e => e.DoCoffre).HasColumnName("DO_Coffre");

                entity.Property(e => e.DoColisage).HasColumnName("DO_Colisage");

                entity.Property(e => e.DoCondition).HasColumnName("DO_Condition");

                entity.Property(e => e.DoContact)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("DO_Contact");

                entity.Property(e => e.DoConversion).HasColumnName("DO_Conversion");

                entity.Property(e => e.DoCoord01)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("DO_Coord01");

                entity.Property(e => e.DoCoord02)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("DO_Coord02");

                entity.Property(e => e.DoCoord03)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("DO_Coord03");

                entity.Property(e => e.DoCoord04)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("DO_Coord04");

                entity.Property(e => e.DoCours)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_Cours");

                entity.Property(e => e.DoDate)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_Date");

                entity.Property(e => e.DoDateExpedition)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_DateExpedition");

                entity.Property(e => e.DoDateLivr)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_DateLivr");

                entity.Property(e => e.DoDateLivrRealisee)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_DateLivrRealisee");

                entity.Property(e => e.DoDebutAbo)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_DebutAbo");

                entity.Property(e => e.DoDebutPeriod)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_DebutPeriod");

                entity.Property(e => e.DoDemandeRegul).HasColumnName("DO_DemandeRegul");

                entity.Property(e => e.DoDevise).HasColumnName("DO_Devise");

                entity.Property(e => e.DoDocType).HasColumnName("DO_DocType");

                entity.Property(e => e.DoDomaine).HasColumnName("DO_Domaine");

                entity.Property(e => e.DoEcart)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_Ecart");

                entity.Property(e => e.DoEscompte).HasColumnName("DO_Escompte");

                entity.Property(e => e.DoEstatut).HasColumnName("DO_EStatut");

                entity.Property(e => e.DoExpedit).HasColumnName("DO_Expedit");

                entity.Property(e => e.DoFactureElec).HasColumnName("DO_FactureElec");

                entity.Property(e => e.DoFactureFile).HasColumnName("DO_FactureFile");

                entity.Property(e => e.DoFactureFrs)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("DO_FactureFrs");

                entity.Property(e => e.DoFinAbo)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_FinAbo");

                entity.Property(e => e.DoFinPeriod)
                    .HasColumnType("datetime")
                    .HasColumnName("DO_FinPeriod");

                entity.Property(e => e.DoGuid).HasColumnName("DO_GUID");

                entity.Property(e => e.DoHeure)
                    .HasMaxLength(9)
                    .IsUnicode(false)
                    .HasColumnName("DO_Heure")
                    .IsFixedLength();

                entity.Property(e => e.DoImprim).HasColumnName("DO_Imprim");

                entity.Property(e => e.DoLangue).HasColumnName("DO_Langue");

                entity.Property(e => e.DoMajCpta).HasColumnName("DO_MajCpta");

                entity.Property(e => e.DoMontantRegle)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_MontantRegle");

                entity.Property(e => e.DoMotif)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("DO_Motif");

                entity.Property(e => e.DoMotifDevis).HasColumnName("DO_MotifDevis");

                entity.Property(e => e.DoNbFacture).HasColumnName("DO_NbFacture");

                entity.Property(e => e.DoNetApayer)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_NetAPayer");

                entity.Property(e => e.DoNoWeb)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_NoWeb");

                entity.Property(e => e.DoPaiementLigne).HasColumnName("DO_PaiementLigne");

                entity.Property(e => e.DoPeriod).HasColumnName("DO_Period");

                entity.Property(e => e.DoPiece)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DO_Piece");

                entity.Property(e => e.DoPieceOrig)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DO_PieceOrig");

                entity.Property(e => e.DoProvenance).HasColumnName("DO_Provenance");

                entity.Property(e => e.DoRef)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_Ref");

                entity.Property(e => e.DoRefPaiement).HasColumnName("DO_RefPaiement");

                entity.Property(e => e.DoRegime).HasColumnName("DO_Regime");

                entity.Property(e => e.DoReliquat).HasColumnName("DO_Reliquat");

                entity.Property(e => e.DoSouche).HasColumnName("DO_Souche");

                entity.Property(e => e.DoStatut).HasColumnName("DO_Statut");

                entity.Property(e => e.DoStatutBap).HasColumnName("DO_StatutBAP");

                entity.Property(e => e.DoTarif).HasColumnName("DO_Tarif");

                entity.Property(e => e.DoTaxe1)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_Taxe1");

                entity.Property(e => e.DoTaxe2)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_Taxe2");

                entity.Property(e => e.DoTaxe3)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_Taxe3");

                entity.Property(e => e.DoTiers)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("DO_Tiers");

                entity.Property(e => e.DoTotalHt)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalHT");

                entity.Property(e => e.DoTotalHtnet)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalHTNet");

                entity.Property(e => e.DoTotalTtc)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TotalTTC");

                entity.Property(e => e.DoTransaction).HasColumnName("DO_Transaction");

                entity.Property(e => e.DoTransfere).HasColumnName("DO_Transfere");

                entity.Property(e => e.DoTxEscompte)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_TxEscompte");

                entity.Property(e => e.DoType).HasColumnName("DO_Type");

                entity.Property(e => e.DoTypeCalcul).HasColumnName("DO_TypeCalcul");

                entity.Property(e => e.DoTypeColis).HasColumnName("DO_TypeColis");

                entity.Property(e => e.DoTypeFrais).HasColumnName("DO_TypeFrais");

                entity.Property(e => e.DoTypeFranco).HasColumnName("DO_TypeFranco");

                entity.Property(e => e.DoTypeLigneFrais).HasColumnName("DO_TypeLigneFrais");

                entity.Property(e => e.DoTypeLigneFranco).HasColumnName("DO_TypeLigneFranco");

                entity.Property(e => e.DoTypeTaux1).HasColumnName("DO_TypeTaux1");

                entity.Property(e => e.DoTypeTaux2).HasColumnName("DO_TypeTaux2");

                entity.Property(e => e.DoTypeTaux3).HasColumnName("DO_TypeTaux3");

                entity.Property(e => e.DoTypeTaxe1).HasColumnName("DO_TypeTaxe1");

                entity.Property(e => e.DoTypeTaxe2).HasColumnName("DO_TypeTaxe2");

                entity.Property(e => e.DoTypeTaxe3).HasColumnName("DO_TypeTaxe3");

                entity.Property(e => e.DoTypeTransac).HasColumnName("DO_TypeTransac");

                entity.Property(e => e.DoValFrais)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_ValFrais");

                entity.Property(e => e.DoValFranco)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DO_ValFranco");

                entity.Property(e => e.DoValide).HasColumnName("DO_Valide");

                entity.Property(e => e.DoVentile).HasColumnName("DO_Ventile");

                entity.Property(e => e.EtNo).HasColumnName("ET_No");

                entity.Property(e => e.LiNo).HasColumnName("LI_No");

                entity.Property(e => e.MrNo).HasColumnName("MR_No");

                entity.Property(e => e.NCatCompta).HasColumnName("N_CatCompta");

                entity.Property(e => e.Type)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("TYPE");
            });

            modelBuilder.Entity<MsAPointage>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_POINTAGE");

                entity.Property(e => e.ArRef)
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.DlDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("DL_Design");

                entity.Property(e => e.DlQte)
                    .HasColumnType("numeric(24, 6)")
                    .HasColumnName("DL_Qte");

                entity.Property(e => e.DoDomaine).HasColumnName("DO_Domaine");

                entity.Property(e => e.DoPiece)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("DO_Piece");

                entity.Property(e => e.DoType).HasColumnName("DO_Type");

                entity.Property(e => e.LsNoSerie)
                    .HasMaxLength(31)
                    .IsUnicode(false)
                    .HasColumnName("LS_NoSerie");
            });

            modelBuilder.Entity<MsATiers>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_A_TIERS");

                entity.Property(e => e.Activite)
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasColumnName("ACTIVITE");

                entity.Property(e => e.CodePros)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("CodePROS");

                entity.Property(e => e.Intitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("INTITULE");

                entity.Property(e => e.Typss).HasColumnName("TYPSs");
            });

            modelBuilder.Entity<MsArticlesFinal>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_Articles_FINAL");

                entity.Property(e => e.ArDesign)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("AR_Design");

                entity.Property(e => e.ArRef)
                    .IsRequired()
                    .HasMaxLength(19)
                    .IsUnicode(false)
                    .HasColumnName("AR_Ref");

                entity.Property(e => e.CtIntitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("CT_Intitule");

                entity.Property(e => e.CtNum)
                    .IsRequired()
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("CT_Num");

                entity.Property(e => e.FaCodeFamille)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasColumnName("FA_CodeFamille");
            });

            modelBuilder.Entity<MsTiers>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("MS_TIERS");

                entity.Property(e => e.Activite)
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasColumnName("ACTIVITE");

                entity.Property(e => e.CodePros)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("CodePROS");

                entity.Property(e => e.Intitule)
                    .HasMaxLength(69)
                    .IsUnicode(false)
                    .HasColumnName("INTITULE");

                entity.Property(e => e.Typss).HasColumnName("TYPSs");
            });

            modelBuilder.Entity<View1>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("View_1");

                entity.Property(e => e.DlNoOut).HasColumnName("DL_NoOut");

                entity.Property(e => e.DoDomaine).HasColumnName("DO_Domaine");

                entity.Property(e => e.DoType).HasColumnName("DO_Type");

                entity.Property(e => e.Expr1)
                    .HasMaxLength(19)
                    .IsUnicode(false);

                entity.Property(e => e.LsNoSerie)
                    .HasMaxLength(31)
                    .IsUnicode(false)
                    .HasColumnName("LS_NoSerie");
            });
            modelBuilder.Entity<F_Lotserie>(entity =>
            {
                entity.ToTable("F_LOTSERIE"); // Nom de la table dans la base de données

                entity.HasKey(e => new { e.AR_Ref, e.LS_NoSerie }); // Clé primaire composite

                entity.Property(e => e.AR_Ref)
                      .HasColumnName("AR_Ref")
                      .HasMaxLength(19)
                      .IsRequired();

                entity.Property(e => e.LS_NoSerie)
                      .HasColumnName("LS_NoSerie")
                      .HasMaxLength(31)
                      .IsRequired();

                entity.Property(e => e.LS_Peremption)
                      .HasColumnName("LS_Peremption")
                      .HasColumnType("datetime");

                entity.Property(e => e.LS_Fabrication)
                      .HasColumnName("LS_Fabrication")
                      .HasColumnType("datetime");

                entity.Property(e => e.LS_Qte)
                      .HasColumnName("LS_Qte")
                      .HasColumnType("numeric(24, 6)");

                entity.Property(e => e.LS_QteRestant)
                      .HasColumnName("LS_QteRestant")
                      .HasColumnType("numeric(24, 6)");

                entity.Property(e => e.LS_QteRes)
                      .HasColumnName("LS_QteRes")
                      .HasColumnType("numeric(24, 6)");
            });

            // Configuration de la table F_Docligne
            modelBuilder.Entity<F_Docligne>(entity =>
            {
                entity.ToTable("F_DOCLIGNE"); // Nom de la table dans la base de données

                entity.HasKey(e => new { e.DO_Domaine, e.DO_Type, e.DO_Piece }); // Clé primaire composite

                entity.Property(e => e.DO_Domaine)
                      .HasColumnName("DO_Domaine")
                      .IsRequired();

                entity.Property(e => e.DO_Type)
                      .HasColumnName("DO_Type")
                      .IsRequired();

                entity.Property(e => e.CT_Num)
                      .HasColumnName("CT_Num")
                      .HasMaxLength(17)
                      .IsRequired();

                entity.Property(e => e.DO_Piece)
                      .HasColumnName("DO_Piece")
                      .HasMaxLength(13)
                      .IsRequired();

                entity.Property(e => e.DO_Date)
                      .HasColumnName("DO_Date")
                      .HasColumnType("datetime");

                entity.Property(e => e.DO_Ref)
                      .HasColumnName("DO_Ref")
                      .HasMaxLength(17);

                entity.Property(e => e.AR_Ref)
                      .HasColumnName("AR_Ref")
                      .HasMaxLength(19);

                entity.Property(e => e.EU_Qte)
                      .HasColumnName("EU_Qte")
                      .HasColumnType("numeric(24, 6)");
            });

            // Ajoutez les autres configurations existantes ici
        
    

    OnModelCreatingPartial(modelBuilder);

        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}