// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MbArticle
    {
        public string ArRef { get; set; }
        public string ArDesign { get; set; }
        public string? Marque { get; set; }
        public string? CtNum { get; set; }
        public string? CtIntitule { get; set; }
        public string? AfRefFourniss { get; set; }
        public int? DeNo { get; set; }
        public decimal? AsQteMini { get; set; }
        public decimal? AsQteMaxi { get; set; }
        public decimal? AsQteSto { get; set; }
        public decimal? AsQteRes { get; set; }
        public decimal? ArPrixAch { get; set; }
        public decimal? ArPrixVen { get; set; }
        public decimal? ArPunet { get; set; }
        public string? FaCodeFamille { get; set; }
        public short? ArSommeil { get; set; } // Ajouté
        public string? CgNumPrinc { get; set; } // Ajouté
        public short? TypeStock { get; set; } // Ajouté
        public string? AR_CodeBarre { get; set; }

    }
}