// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MbMouv
    {
        public short? DoDomaine { get; set; }
        public short? DoType { get; set; }
        public string DoPiece { get; set; }
        public DateTime? DoDate { get; set; }
        public string DoRef { get; set; }
        public string DoTiers { get; set; }
        public string CtIntitule { get; set; }
        public int? CoNo { get; set; }
        public short? DoDevise { get; set; }
        public string CtNumPayeur { get; set; }
        public decimal? DoTotalHt { get; set; }
        public decimal? DoTotalHtnet { get; set; }
        public decimal? DoTotalTtc { get; set; }
        public decimal? DoNetApayer { get; set; }
        public decimal? DoMontantRegle { get; set; }
        public string ArRef { get; set; }
        public decimal? DlQte { get; set; }
        public decimal? DlQteBc { get; set; }
        public decimal? DlQteBl { get; set; }
        public decimal? EuQte { get; set; }
        public decimal? HtLigne { get; set; }
        public decimal? TtcLigne { get; set; }
        public decimal? DlQtePl { get; set; }
        public decimal? DlQteDe { get; set; }
        public decimal? DlPrixUnitaire { get; set; }
        public decimal? DlCmup { get; set; }
        public decimal? DlPuttc { get; set; }
        public decimal? DlPrixRu { get; set; }
        public int? Depot { get; set; }
    }
}