// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsAArticles
    {
        public string CtIntitule { get; set; }
        public string ArRef { get; set; }
        public string ArDesign { get; set; }
        public string FaCodeFamille { get; set; }
        public decimal? ArPrixVen { get; set; }
        public short? ArPrixTtc { get; set; }
        public int CbMarq { get; set; }
    }
}