// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsAArticleCommercial
    {
        public string Client { get; set; }
        public string Collaborateur { get; set; }
        public string Flag { get; set; }
        public string Prenomcoll { get; set; }
        public string Type { get; set; }
        public string Commercial { get; set; }
        public string ArRef { get; set; }
        public string CtIntitule { get; set; }
        public string ArDesign { get; set; }
        public string FaCodeFamille { get; set; }
    }
}