// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApiTest.Models
{
	public partial class MsAArticle
	{
		public string? ArRef { get; set; }
		public string? ArDesign { get; set; }
		public string? Marque { get; set; }
		public decimal? ArPrixAch { get; set; }
		public decimal? ArPrixVen { get; set; }
		public decimal? ArPunet { get; set; }
		public string? FaCodeFamille { get; set; }
		public short? ArPublie { get; set; } 
		public string? Gl_Text { get; set; }
		public string? Gl_Intitule { get; set; }
		public string Ar_photo { get; set; }
		public string? Famille { get; set; }
		public string? Nouveaute { get; set; }
		public string? Description { get; set; }
		public string? C_Utilisation { get; set; }
		public string? Composition { get; set; }
        public decimal? AS_QteSto { get; set; }
        public short? AR_Sommeil { get; set; }
		public string? Recommande { get; set; }
        public string? AR_CodeBarre { get; set; }
    }
}