// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsAClients
    {
        public string CtNum { get; set; }
        //public string Collaborateur { get; set; }
        public string CtIntitule { get; set; }
        public short? CtType { get; set; }
        public string CtContact { get; set; }
        public string CtClassement { get; set; }
        public string CtQualite { get; set; }
        public string CtAdresse { get; set; }
        public string CtComplement { get; set; }
        public string CtCodePostal { get; set; }
        public string CtVille { get; set; }
        public string CtPays { get; set; }
        public short? CtSommeil { get; set; }
        public string CtEmail { get; set; }
        public string CtSite { get; set; }
        public string CtIdentifiant { get; set; }
        public string CtSiret { get; set; }
        public string CtTelephone { get; set; }
        public string CtCodeRegion { get; set; }
        public int CbMarq { get; set; }
        //public string Prenomcoll { get; set; }
        public short? NCatTarif { get; set; }
    }
}