// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsAEntt
    {
        public short? DoDomaine { get; set; }
        public short? DoType { get; set; }
        public DateTime? DoDate { get; set; }
        public string DoTiers { get; set; }
        public decimal? DoTotalTtc { get; set; }
        public decimal? DoTotalHtnet { get; set; }
		public decimal? DoNetAPayer { get; set; }
		public decimal? DoMontantRegle { get; set; }
       
		public string Marque { get; set; }
        public string Type { get; set; }
        public string Destination { get; set; }
        public string Destinataire { get; set; }
        public int CbMarq { get; set; }
        public string DoPiece { get; set; }
    }
}