// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsALigne
    {
        public short? DoDomaine { get; set; }
        public short DoType { get; set; }
        public string DoPiece { get; set; }
        public DateTime? DoDate { get; set; }
        public string DoRef { get; set; }
        public string ArRef { get; set; }
        public string DlDesign { get; set; }
        public decimal? DlQte { get; set; }
        public decimal? DlQteBc { get; set; }
        public decimal? DlPrixUnitaire { get; set; }
        public decimal? DlPuttc { get; set; }
        public decimal? DlPudevise { get; set; }
        public decimal? DlMontantHt { get; set; }
        public decimal? DlMontantTtc { get; set; }
        public int CbMarq { get; set; }
        public string Utilisateur { get; set; }
    }
}