// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsAPointage
    {
        public string DoPiece { get; set; }
        public short DoType { get; set; }
        public short? DoDomaine { get; set; }
        public string ArRef { get; set; }
        public decimal? DlQte { get; set; }
        public string DlDesign { get; set; }
        public string LsNoSerie { get; set; }
    }
}