// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsArticlesFinal
    {
        public string? ArRef { get; set; }
        public string? CtNum { get; set; }
        public string? CtIntitule { get; set; }
        public string? ArDesign { get; set; }
        public string? FaCodeFamille { get; set; }
    }
}