// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsATiers
    {
        public string CodePros { get; set; }
        public string Intitule { get; set; }
        public string Activite { get; set; }
        public short? Typss { get; set; }
    }
}