// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class MsReclamationweb
    {
        public int Id { get; set; }
        public string Client { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string Rep { get; set; }
        public string Flag1 { get; set; }
        public string Flag2 { get; set; }
        public string Collaborateur { get; set; }
        public DateTime? Date { get; set; }
        public DateTime? Daterep { get; set; }
    }
}