// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiTest.Models
{
    public partial class View1
    {
        public short? DoDomaine { get; set; }
        public short DoType { get; set; }
        public string LsNoSerie { get; set; }
        public string Expr1 { get; set; }
        public int? DlNoOut { get; set; }
    }
}